---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
unzip("H:/My Drive/RWD/Reproducible/RepData_PeerAssessment1/activity.zip")
data <- read.csv("activity.csv")
```

## What is mean total number of steps taken per day?
```{r, results='asis'}
library(dplyr)
daily <- data %>% group_by(date) %>%
  summarize(steps=sum(steps))
hist(daily$steps)
StepsMean <- mean(daily$steps, na.rm=TRUE)
StepsMedian <- median(daily$steps, na.rm=TRUE)
print(paste("Mean number of daily steps:", StepsMean, "; Median number of daily steps:", StepsMedian))
```

## What is the average daily activity pattern?
```{r, results='asis'}
timely <- data %>% group_by(interval) %>%
  summarize(steps=mean(steps, na.rm = TRUE))
with(timely, plot(interval, steps, type="l"))
max_interval <- with(timely, interval[which.max(steps)])
print(paste("5-minute interval with maximum number of steps on average across all the days:", max_interval))
```

## Imputing missing values using mean number of steps in each time interval
```{r, results='asis'}
print(paste("Total number of missing values: ", sum(is.na(data$steps))))
imputedData <- data
imputedData$steps <- rowSums(cbind(data$steps, is.na(data$steps) * timely$steps), na.rm=TRUE)
imputedDaily <- imputedData %>% group_by(date) %>%
  summarize(steps=sum(steps))
hist(imputedDaily$steps)
imputedStepsMean <- mean(imputedDaily$steps, na.rm=TRUE)
imputedStepsMedian <- median(imputedDaily$steps, na.rm=TRUE)
print(paste("After imputation, mean number of daily steps:", imputedStepsMean, ", and median number of daily steps:", imputedStepsMedian))
```

## Are there differences in activity patterns between weekdays and weekends?
```{r, results='asis'}
library(ggplot2)
imputedData$weekday <- ifelse(weekdays(as.Date(imputedData$date)) %in% c("Saturday", "Sunday"), "Weekend", "Weekday")
timely <- imputedData %>% group_by(interval, weekday) %>%
  summarize(steps=mean(steps, na.rm = TRUE))
ggplot(timely, aes(x = interval, y = steps)) +
  geom_point(show.legend = FALSE) +
  geom_line()+
  facet_wrap(~weekday)
```